---
all:
  vars:
    env_name: prod
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
  children:
    imp_clients:
      hosts:
        imp-client-prod:
          ansible_host: 10.0.120.10
    imp_servers:
      hosts:
        imp-server-prod:
          ansible_host: 10.0.120.11
    imp_databases:
      hosts:
        imp-db-prod:
          ansible_host: 10.0.120.12
    imp_storage:
      hosts:
        imp-minio-prod:
          ansible_host: 10.0.120.13
    imp_monitoring:
      hosts: {}
