---
grafana_admin_user: admin
grafana_admin_password: ""  # [VAULT] â€” set from Vault in QA/Prod
grafana_domain: "monitoring.imp.razorwire-productions.com"
grafana_root_url: "https://{{ grafana_domain }}/"
