---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart orchestrator
  service:
    name: "{{ orchestrator_service_name }}"
    state: restarted

- name: apply netplan
  command: netplan apply
