---
all:
  vars:
    env_name: dev
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
  children:
    imp_clients:
      hosts:
        imp-client-dev:
          ansible_host: 10.0.100.10
    imp_servers:
      hosts:
        imp-server-dev:
          ansible_host: 10.0.100.11
    imp_databases:
      hosts:
        imp-db-dev:
          ansible_host: 10.0.100.12
    imp_storage:
      hosts:
        imp-minio-dev:
          ansible_host: 10.0.100.13
    imp_monitoring:
      hosts: {}
