---
app_name: "imp"
prometheus_version: "2.48.1"
prometheus_retention: "30d"
monitoring_network: "10.0.5.0/24"

# Scrape targets â€” populated by Terraform inventory
# Override per environment in group_vars
monitoring_targets:
  node:
    - "{{ app_name }}-client-{{ environment_name }}:9100"
    - "{{ app_name }}-server-{{ environment_name }}:9100"
    - "{{ app_name }}-db-{{ environment_name }}:9100"
    - "{{ app_name }}-minio-{{ environment_name }}:9100"
    - "{{ app_name }}-monitoring-{{ environment_name }}:9100"
  app:
    - "{{ app_name }}-server-{{ environment_name }}:2727"
