---
vault_version: "1.15.4"
vault_user: vault
vault_group: vault
vault_config_dir: /etc/vault.d
vault_data_dir: /opt/vault/data
vault_log_dir: /var/log/vault
vault_address: "0.0.0.0"
vault_port: 8200
vault_cluster_port: 8201
vault_tls_disable: false
vault_tls_cert_file: /etc/vault.d/tls/vault-cert.pem
vault_tls_key_file: /etc/vault.d/tls/vault-key.pem
vault_storage_backend: file
