---
all:
  vars:
    env_name: shared
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new -o ProxyJump=root@prx002.razorwire-productions.com'
  children:
    imp_vault:
      hosts:
        imp-vault:
          ansible_host: 10.0.5.40
    imp_runner:
      hosts:
        imp-runner:
          ansible_host: 10.0.5.41
          runner_env_nics:
            - interface: ens19
              address: 10.0.100.1/24
              subnet: 10.0.100.0/24
              gateway: 10.0.100.254
              metric: 200
            - interface: ens20
              address: 10.0.110.1/24
              subnet: 10.0.110.0/24
              gateway: 10.0.110.254
              metric: 210
            - interface: ens21
              address: 10.0.120.1/24
              subnet: 10.0.120.0/24
              gateway: 10.0.120.254
              metric: 220
    imp_orchestrator:
      hosts:
        imp-orchestrator:
          ansible_host: 10.0.5.42
          orchestrator_env_nics:
            - interface: ens19
              address: 10.0.100.2/24
              subnet: 10.0.100.0/24
              gateway: 10.0.100.254
              metric: 200
            - interface: ens20
              address: 10.0.110.2/24
              subnet: 10.0.110.0/24
              gateway: 10.0.110.254
              metric: 210
            - interface: ens21
              address: 10.0.120.2/24
              subnet: 10.0.120.0/24
              gateway: 10.0.120.254
              metric: 220
