---
all:
  vars:
    env_name: shared
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new -o ProxyJump=root@prx002.razorwire-productions.com'
    app_name: "imp"
    group_vault: "pw_vault"
    group_runner: "pw_runner"
    group_orchestrator: "pw_orchestrator"
  children:
    pw_vault:
      hosts:
        pw-vault:
          ansible_host: 10.0.5.40
    pw_runner:
      hosts:
        pw-runner:
          ansible_host: 10.0.5.41
          runner_env_nics:
            - interface: ens19
              address: 10.0.100.3/24
              subnet: 10.0.100.0/24
              gateway: 10.0.100.1
              metric: 200
            - interface: ens20
              address: 10.0.110.3/24
              subnet: 10.0.110.0/24
              gateway: 10.0.110.1
              metric: 210
            - interface: ens21
              address: 10.0.120.3/24
              subnet: 10.0.120.0/24
              gateway: 10.0.120.1
              metric: 220
    pw_orchestrator:
      hosts:
        pw-orchestrator:
          ansible_host: 10.0.5.42
          orchestrator_env_nics:
            - interface: ens19
              address: 10.0.100.2/24
              subnet: 10.0.100.0/24
              gateway: 10.0.100.1
              metric: 200
            - interface: ens20
              address: 10.0.110.2/24
              subnet: 10.0.110.0/24
              gateway: 10.0.110.1
              metric: 210
            - interface: ens21
              address: 10.0.120.2/24
              subnet: 10.0.120.0/24
              gateway: 10.0.120.1
              metric: 220
