---
app_server_base_dir: /opt/imp-server
app_server_releases_dir: "{{ app_server_base_dir }}/releases"
app_server_shared_dir: "{{ app_server_base_dir }}/shared"
app_server_current_link: "{{ app_server_base_dir }}/current"
app_server_keep_releases: 3
app_server_port: 2727
app_server_service_name: imp-server
deploy_user: deploy
