---
all:
  vars:
    env_name: qa
    ansible_user: deploy
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
  children:
    imp_clients:
      hosts:
        imp-client-qa:
          ansible_host: 10.0.110.10
    imp_servers:
      hosts:
        imp-server-qa:
          ansible_host: 10.0.110.11
    imp_databases:
      hosts:
        imp-db-qa:
          ansible_host: 10.0.110.12
    imp_storage:
      hosts:
        imp-minio-qa:
          ansible_host: 10.0.110.13
    imp_monitoring:
      hosts: {}
